include(FetchContent)

function(add_external_library name dir repo tag build)
	if(NOT EXISTS ${dir}/CMakeLists.txt AND NOT EXISTS ${dir}/README.md)
		message(STATUS "Cloning ${name} from ${repo} to ${dir}")
		if(tag)
			FetchContent_Declare(${name} GIT_REPOSITORY ${repo} GIT_TAG ${tag} SOURCE_DIR ${dir})
		else()
			FetchContent_Declare(${name} GIT_REPOSITORY ${repo} SOURCE_DIR ${dir})
		endif()
		FetchContent_MakeAvailable(${name})
	endif()
	if(EXISTS ${dir}/CMakeLists.txt)
		message(STATUS "Using existing ${name} at ${dir}")
		if(${build})
			message(STATUS "Building external library: ${name}")
			add_subdirectory(${dir} ${CMAKE_BINARY_DIR}/external/${name})
		endif()
	endif()
endfunction()