include(FetchContent)

function(add_external_library name dir repo tag build file)
	
	if(DEFINED USE_SSH)
		SET(GIT_REPO git@github.com:${repo}.git)
	else()
		SET(GIT_REPO https://github.com/${repo})
	endif()

	message(STATUS "${CMAKE_PROJECT_NAME}: name: '${name}' dir: '${dir}' repo: '${GIT_REPO}' tag: '${tag}' build: '${build}' file: '${file}'")

	
	if(NOT EXISTS ${dir}/${file})
		message(STATUS "Cloning ${name} from ${GIT_REPO} to ${dir}")
		if(tag)
			FetchContent_Declare(${name} GIT_REPOSITORY ${GIT_REPO} GIT_TAG ${tag} SOURCE_DIR ${dir})
		else()
			FetchContent_Declare(${name} GIT_REPOSITORY ${GIT_REPO} SOURCE_DIR ${dir})
		endif()
		FetchContent_Populate(${name})
	endif()
	if(EXISTS ${dir}/${file})
		message(STATUS "Using existing ${name} at ${dir}")
		if(${build})
			message(STATUS "Building external library: ${name}")
			if(NOT TARGET ${name})
				add_subdirectory(${dir} ${CMAKE_BINARY_DIR}/external/${name})
			else()
				message(STATUS "External library ${name} already added as target")
			endif()
		endif()
	endif()
endfunction()